services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=bitscape
    ports:
      - '5432:5432'
  adminer:
    image: 'adminer:latest'
    ports:
      - '8080:8080'
    