/* eslint-disable prettier/prettier */
import { Injectable } from '@nestjs/common';

@Injectable()
export class AppService {
  private amd = {
    "zen4": [
      {
        "name": 'Ryzen 9 7950X',
        "cores": "16",
        "threads": "32",
        "maxfrec": "5.70GHz",
        "tdp": "170W",
        "socket": "AM5",
        "arq": "Zen 4",
        "process": "5nm",
        "l3": "64MB",
        "year": "2022",
        "igpu": "No"
      },
      {
        "name": "Ryzen 9 7900X",
        "cores": "12",
        "threads": "24",
        "maxfrec": "5.60GHz",
        "tdp": "170W",
        "socket": "AM5",
        "arq": "Zen 4",
        "process": "5nm",
        "l3": "64MB",
        "year": "2022",
        "igpu": "No"
      },
      {
        "name": "Ryzen 7 7800X3D",
        "cores": "8",
        "threads": "16",
        "maxfrec": "5.0GHz",
        "tdp": "120W",
        "socket": "AM5",
        "arq": "Zen 4",
        "process": "5nm",
        "l3": "96MB (Con tecnologia 3D V-cache)",
        "year": "2022",
        "igpu": "No"
      },
      {
        "name": "Ryzen 7 7700X",
        "cores": "8",
        "threads": "16",
        "maxfrec": "5.4 GHz",
        "tdp": "105W",
        "socket": "AM5",
        "arq": "Zen 4",
        "process": "5nm",
        "l3": "32 MB",
        "year": "2022",
        "igpu": "No"
      },
      {
        "name": "Ryzen 5 7600X",
        "cores": "6",
        "threads": "12",
        "maxfrec": "5.3 GHz",
        "tdp": "105W",
        "socket": "AM5",
        "arq": "Zen 4",
        "process": "5nm",
        "l3": "32 MB",
        "year": "2022",
        "igpu": "No"
      },
      {
        "name": "Ryzen 5 7600",
        "cores": "6",
        "threads": "12",
        "maxfrec": "5.1 GHz",
        "tdp": "65W",
        "socket": "AM5",
        "arq": "Zen 4",
        "process": "5nm",
        "l3": "32 MB",
        "year": "2022",
        "igpu": "Si"
      },
      {
        "name": "Ryzen 7 7700",
        "cores": "8",
        "threads": "16",
        "maxfrec": "5.3 GHz",
        "tdp": "65W",
        "socket": "AM5",
        "arq": "Zen 4",
        "process": "5nm",
        "l3": "32 MB",
        "year": "2022",
        "igpu": "Si"
      },
      {
        "name": "Ryzen 9 7900",
        "cores": "12",
        "threads": "24",
        "maxfrec": "5.4 GHz",
        "tdp": "65W",
        "socket": "AM5",
        "arq": "Zen 4",
        "process": "5nm",
        "l3": "64 MB",
        "year": "2022",
        "igpu": "Si"
      }
    ],
    "zen3": [
      {
        "name": "Ryzen 9 5950X",
        "cores": "16",
        "threads": "32",
        "maxfrec": "4.9 GHz",
        "tdp": "105W",
        "socket": "AM4",
        "arq": "Zen 3",
        "process": "7nm",
        "l3": "64 MB",
        "year": "2020",
        "igpu": "No"
      },
      {
        "name": "Ryzen 9 5900X",
        "cores": "12",
        "threads": "24",
        "maxfrec": "4.8 GHz",
        "tdp": "105W",
        "socket": "AM4",
        "arq": "Zen 3",
        "process": "7nm",
        "l3": "64 MB",
        "year": "2020",
        "igpu": "No"
      },
      {
        "name": "Ryzen 7 5800X3D",
        "cores": "8",
        "threads": "16",
        "maxfrec": "4.5 GHz",
        "tdp": "105W",
        "socket": "AM4",
        "arq": "Zen 3",
        "process": "7nm",
        "l3": "96 MB",
        "year": "2022",
        "igpu": "No"
      },
      {
        "name": "Ryzen 7 5800X",
        "cores": "8",
        "threads": "16",
        "maxfrec": "4.7 GHz",
        "tdp": "105W",
        "socket": "AM4",
        "arq": "Zen 3",
        "process": "7nm",
        "l3": "32 MB",
        "year": "2020",
        "igpu": "No"
      },
      {
        "name": "Ryzen 5 5600X",
        "cores": "6",
        "threads": "12",
        "maxfrec": "4.6 GHz",
        "tdp": "65W",
        "socket": "AM4",
        "arq": "Zen 3",
        "process": "7nm",
        "l3": "32 MB",
        "year": "2020",
        "igpu": "No"
      },
      {
        "name": "Ryzen 5 5600",
        "cores": "6",
        "threads": "12",
        "maxfrec": "4.4 GHz",
        "tdp": "65W",
        "socket": "AM4",
        "arq": "Zen 3",
        "process": "7nm",
        "l3": "32 MB",
        "year": "2021",
        "igpu": "No"
      },
      {
        "name": "Ryzen 7 5700G",
        "cores": "8",
        "threads": "16",
        "maxfrec": "4.6 GHz",
        "tdp": "65W",
        "socket": "AM4",
        "arq": "Zen 3",
        "process": "7nm",
        "l3": "16 MB",
        "year": "2021",
        "igpu": "Si"
      },
      {
        "name": "Ryzen 5 5600G",
        "cores": "6",
        "threads": "12",
        "maxfrec": "4.4 GHz",
        "tdp": "65W",
        "socket": "AM4",
        "arq": "Zen 3",
        "process": "7nm",
        "l3": "16 MB",
        "year": "2021",
        "igpu": "Si"
      },
      {
        "name": "Ryzen 3 5300G",
        "cores": "4",
        "threads": "8",
        "maxfrec": "4.2 GHz",
        "tdp": "65W",
        "socket": "AM4",
        "arq": "Zen 3",
        "process": "7nm",
        "l3": "8 MB",
        "year": "2021",
        "igpu": "Si"
      }
    ],
    "zen2": [
      {
        "name": "Ryzen 9 3950X",
        "cores": "16",
        "threads": "32",
        "maxfrec": "4.7 GHz",
        "tdp": "105W",
        "socket": "AM4",
        "arq": "Zen 2",
        "process": "7nm",
        "l3": "64 MB",
        "year": "2019",
        "igpu": "No"
      },
      {
        "name": "Ryzen 9 3900X",
        "cores": "12",
        "threads": "24",
        "maxfrec": "4.6 GHz",
        "tdp": "105W",
        "socket": "AM4",
        "arq": "Zen 2",
        "process": "7nm",
        "l3": "64 MB",
        "year": "2019",
        "igpu": "No"
      },
      {
        "name": "Ryzen 7 3800X",
        "cores": "8",
        "threads": "16",
        "maxfrec": "4.5 GHz",
        "tdp": "105W",
        "socket": "AM4",
        "arq": "Zen 2",
        "process": "7nm",
        "l3": "32 MB",
        "year": "2019",
        "igpu": "No"
      },
      {
        "name": "Ryzen 7 3700X",
        "cores": "8",
        "threads": "16",
        "maxfrec": "4.4 GHz",
        "tdp": "65W",
        "socket": "AM4",
        "arq": "Zen 2",
        "process": "7nm",
        "l3": "32 MB",
        "year": "2019",
        "igpu": "No"
      },
      {
        "name": "Ryzen 5 3600X",
        "cores": "6",
        "threads": "12",
        "maxfrec": "4.4 GHz",
        "tdp": "95W",
        "socket": "AM4",
        "arq": "Zen 2",
        "process": "7nm",
        "l3": "32 MB",
        "year": "2019",
        "igpu": "No"
      },
      {
        "name": "Ryzen 5 3600",
        "cores": "6",
        "threads": "12",
        "maxfrec": "4.2 GHz",
        "tdp": "65W",
        "socket": "AM4",
        "arq": "Zen 2",
        "process": "7nm",
        "l3": "32 MB",
        "year": "2019",
        "igpu": "No"
      },
      {
        "name": "Ryzen 5 3500X",
        "cores": "6",
        "threads": "6",
        "maxfrec": "4.1 GHz",
        "tdp": "65W",
        "socket": "AM4",
        "arq": "Zen 2",
        "process": "7nm",
        "l3": "32 MB",
        "year": "2019",
        "igpu": "No"
      },
      {
        "name": "Ryzen 3 3300X",
        "cores": "4",
        "threads": "8",
        "maxfrec": "4.3 GHz",
        "tdp": "65W",
        "socket": "AM4",
        "arq": "Zen 2",
        "process": "7nm",
        "l3": "16 MB",
        "year": "2020",
        "igpu": "No"
      },
      {
        "name": "Ryzen 3 3100",
        "cores": "4",
        "threads": "8",
        "maxfrec": "3.9 GHz",
        "tdp": "65W",
        "socket": "AM4",
        "arq": "Zen 2",
        "process": "7nm",
        "l3": "16 MB",
        "year": "2020",
        "igpu": "No"
      },
    ],
    "zen+": [
      {
        "name": "Ryzen 5 3400G",
        "cores": "4",
        "threads": "8",
        "maxfrec": "4.2 GHz",
        "tdp": "65W",
        "socket": "AM4",
        "arq": "Zen+",
        "process": "12nm",
        "l3": "4 MB",
        "year": "2019",
        "igpu": "Si"
      },
      {
        "name": "Ryzen 3 3200G",
        "cores": "4",
        "threads": "4",
        "maxfrec": "4.0 GHz",
        "tdp": "65W",
        "socket": "AM4",
        "arq": "Zen+",
        "process": "12nm",
        "l3": "4 MB",
        "year": "2019",
        "igpu": "Si"
      },
      {
        "name": "Ryzen 7 2700X",
        "cores": "8",
        "threads": "16",
        "maxfrec": "4.3 GHz",
        "tdp": "105W",
        "socket": "AM4",
        "arq": "Zen+",
        "process": "12nm",
        "l3": "16 MB",
        "year": "2018",
        "igpu": "No"
      },
      {
        "name": "Ryzen 7 2700",
        "cores": "8",
        "threads": "16",
        "maxfrec": "4.1 GHz",
        "tdp": "65W",
        "socket": "AM4",
        "arq": "Zen+",
        "process": "12nm",
        "l3": "16 MB",
        "year": "2018",
        "igpu": "No"
      },
      {
        "name": "Ryzen 5 2600X",
        "cores": "6",
        "threads": "12",
        "maxfrec": "4.2 GHz",
        "tdp": "95W",
        "socket": "AM4",
        "arq": "Zen+",
        "process": "12nm",
        "l3": "16 MB",
        "year": "2018",
        "igpu": "No"
      },
      {
        "name": "Ryzen 5 2600",
        "cores": "6",
        "threads": "12",
        "maxfrec": "4.1 GHz",
        "tdp": "65W",
        "socket": "AM4",
        "arq": "Zen+",
        "process": "12nm",
        "l3": "16 MB",
        "year": "2018",
        "igpu": "No"
      },
      {
        "name": "Ryzen 5 2500X",
        "cores": "4",
        "threads": "8",
        "maxfrec": "4.0 GHz",
        "tdp": "65W",
        "socket": "AM4",
        "arq": "Zen+",
        "process": "12nm",
        "l3": "8 MB",
        "year": "2018",
        "igpu": "No"
      },
      {
        "name": "Ryzen 3 2300X",
        "cores": "4",
        "threads": "4",
        "maxfrec": "4.0 GHz",
        "tdp": "65W",
        "socket": "AM4",
        "arq": "Zen+",
        "process": "12nm",
        "l3": "8 MB",
        "year": "2018",
        "igpu": "No"
      }
    ],
    "zen": [
      {
        "name": "Ryzen 5 2400G",
        "cores": "4",
        "threads": "8",
        "maxfrec": "3.9 GHz",
        "tdp": "65W",
        "socket": "AM4",
        "arq": "Zen",
        "process": "14nm",
        "l3": "4 MB",
        "year": "2018",
        "igpu": "Si"
      },
      {
        "name": "Ryzen 3 2200G",
        "cores": "4",
        "threads": "4",
        "maxfrec": "3.7 GHz",
        "tdp": "65W",
        "socket": "AM4",
        "arq": "Zen",
        "process": "14nm",
        "l3": "4 MB",
        "year": "2018",
        "igpu": "Si"
      },
      {
        "name": "Ryzen 7 1800X",
        "cores": "8",
        "threads": "16",
        "maxfrec": "4.0 GHz",
        "tdp": "95W",
        "socket": "AM4",
        "arq": "Zen",
        "process": "14nm",
        "l3": "16 MB",
        "year": "2017",
        "igpu": "No"
      },
      {
        "name": "Ryzen 7 1700X",
        "cores": "8",
        "threads": "16",
        "maxfrec": "3.8 GHz",
        "tdp": "95W",
        "socket": "AM4",
        "arq": "Zen",
        "process": "14nm",
        "l3": "16 MB",
        "year": "2017",
        "igpu": "No"
      },
      {
        "name": "Ryzen 7 1700",
        "cores": "8",
        "threads": "16",
        "maxfrec": "3.7 GHz",
        "tdp": "65W",
        "socket": "AM4",
        "arq": "Zen",
        "process": "14nm",
        "l3": "16 MB",
        "year": "2017",
        "igpu": "No"
      }
    ]
  }
  private intel = {
    "raptor_lake_refresh": [
      {
        "name": "Core i9-14900K",
        "cores": "24",
        "threads": "32",
        "maxfrec": "5.8 GHz",
        "tdp": "125W",
        "socket": "LGA 1700",
        "arq": "Raptor Lake Refresh",
        "process": "Intel 7",
        "l3": "36 MB",
        "year": "2024",
        "igpu": "Intel UHD Graphics 770"
    },
    {
        "name": "Core i9-14900KF",
        "cores": "24",
        "threads": "32",
        "maxfrec": "5.8 GHz",
        "tdp": "125W",
        "socket": "LGA 1700",
        "arq": "Raptor Lake Refresh",
        "process": "Intel 7",
        "l3": "36 MB",
        "year": "2024",
        "igpu": "No"
    },
    {
        "name": "Core i7-14700K",
        "cores": "16",
        "threads": "24",
        "maxfrec": "5.6 GHz",
        "tdp": "125W",
        "socket": "LGA 1700",
        "arq": "Raptor Lake Refresh",
        "process": "Intel 7",
        "l3": "30 MB",
        "year": "2024",
        "igpu": "Intel UHD Graphics 770"
    },
    {
        "name": "Core i7-14700KF",
        "cores": "16",
        "threads": "24",
        "maxfrec": "5.6 GHz",
        "tdp": "125W",
        "socket": "LGA 1700",
        "arq": "Raptor Lake Refresh",
        "process": "Intel 7",
        "l3": "30 MB",
        "year": "2024",
        "igpu": "No"
    },
    {
        "name": "Core i5-14600K",
        "cores": "14",
        "threads": "20",
        "maxfrec": "5.3 GHz",
        "tdp": "125W",
        "socket": "LGA 1700",
        "arq": "Raptor Lake Refresh",
        "process": "Intel 7",
        "l3": "24 MB",
        "year": "2024",
        "igpu": "Intel UHD Graphics 770"
    },
    {
        "name": "Core i5-14600KF",
        "cores": "14",
        "threads": "20",
        "maxfrec": "5.3 GHz",
        "tdp": "125W",
        "socket": "LGA 1700",
        "arq": "Raptor Lake Refresh",
        "process": "Intel 7",
        "l3": "24 MB",
        "year": "2024",
        "igpu": "No"
    }
    ],
    "raptor_lake": [
      {
        "name": "Core i9-13900K",
        "cores": "24",
        "threads": "32",
        "maxfrec": "5.8 GHz",
        "tdp": "125W",
        "socket": "LGA 1700",
        "arq": "Raptor Lake",
        "process": "Intel 7",
        "l3": "36 MB",
        "year": "2022",
        "igpu": "Intel UHD Graphics 770"
    },
    {
        "name": "Core i9-13900KF",
        "cores": "24",
        "threads": "32",
        "maxfrec": "5.8 GHz",
        "tdp": "125W",
        "socket": "LGA 1700",
        "arq": "Raptor Lake",
        "process": "Intel 7",
        "l3": "36 MB",
        "year": "2022",
        "igpu": "No"
    },
    {
        "name": "Core i7-13700K",
        "cores": "16",
        "threads": "24",
        "maxfrec": "5.4 GHz",
        "tdp": "125W",
        "socket": "LGA 1700",
        "arq": "Raptor Lake",
        "process": "Intel 7",
        "l3": "30 MB",
        "year": "2022",
        "igpu": "Intel UHD Graphics 770"
    },
    {
        "name": "Core i5-13600K",
        "cores": "14",
        "threads": "20",
        "maxfrec": "5.1 GHz",
        "tdp": "125W",
        "socket": "LGA 1700",
        "arq": "Raptor Lake",
        "process": "Intel 7",
        "l3": "24 MB",
        "year": "2022",
        "igpu": "Intel UHD Graphics 770"
    },
    {
        "name": "Core i5-13400",
        "cores": "10",
        "threads": "16",
        "maxfrec": "4.6 GHz",
        "tdp": "65W",
        "socket": "LGA 1700",
        "arq": "Raptor Lake",
        "process": "Intel 7",
        "l3": "20 MB",
        "year": "2023",
        "igpu": "Intel UHD Graphics 730"
    },
    {
        "name": "Core i3-13100",
        "cores": "4",
        "threads": "8",
        "maxfrec": "4.5 GHz",
        "tdp": "60W",
        "socket": "LGA 1700",
        "arq": "Raptor Lake",
        "process": "Intel 7",
        "l3": "12 MB",
        "year": "2023",
        "igpu": "Intel UHD Graphics 730"
    }
    ],
    "alder_lake": [
      {
        "name": "Core i9-12900K",
        "cores": "24",
        "threads": "32",
        "maxfrec": "5.2 GHz",
        "tdp": "125W",
        "socket": "LGA 1700",
        "arq": "Alder Lake",
        "process": "Intel 7",
        "l3": "30 MB",
        "year": "2021",
        "igpu": "Intel UHD Graphics 770"
    },
    {
        "name": "Core i9-12900KF",
        "cores": "24",
        "threads": "32",
        "maxfrec": "5.2 GHz",
        "tdp": "125W",
        "socket": "LGA 1700",
        "arq": "Alder Lake",
        "process": "Intel 7",
        "l3": "30 MB",
        "year": "2021",
        "igpu": "No"
    },
    {
        "name": "Core i7-12700K",
        "cores": "12",
        "threads": "20",
        "maxfrec": "5.0 GHz",
        "tdp": "125W",
        "socket": "LGA 1700",
        "arq": "Alder Lake",
        "process": "Intel 7",
        "l3": "25 MB",
        "year": "2021",
        "igpu": "Intel UHD Graphics 770"
    },
    {
        "name": "Core i5-12600K",
        "cores": "10",
        "threads": "16",
        "maxfrec": "4.9 GHz",
        "tdp": "125W",
        "socket": "LGA 1700",
        "arq": "Alder Lake",
        "process": "Intel 7",
        "l3": "20 MB",
        "year": "2021",
        "igpu": "Intel UHD Graphics 770"
    },
    {
        "name": "Core i5-12400",
        "cores": "6",
        "threads": "12",
        "maxfrec": "4.4 GHz",
        "tdp": "65W",
        "socket": "LGA 1700",
        "arq": "Alder Lake",
        "process": "Intel 7",
        "l3": "18 MB",
        "year": "2022",
        "igpu": "Intel UHD Graphics 730"
    },
    {
        "name": "Core i3-12100",
        "cores": "4",
        "threads": "8",
        "maxfrec": "4.3 GHz",
        "tdp": "60W",
        "socket": "LGA 1700",
        "arq": "Alder Lake",
        "process": "Intel 7",
        "l3": "12 MB",
        "year": "2022",
        "igpu": "Intel UHD Graphics 730"
    }
    ],
    "rocket_lake": [
      {
        "name": "Core i9-11900K",
        "cores": "8",
        "threads": "16",
        "maxfrec": "5.3 GHz",
        "tdp": "125W",
        "socket": "LGA 1200",
        "arq": "Rocket Lake",
        "process": "14nm",
        "l3": "16 MB",
        "year": "2021",
        "igpu": "Intel UHD Graphics 750"
    },
    {
        "name": "Core i7-11700K",
        "cores": "8",
        "threads": "16",
        "maxfrec": "5.0 GHz",
        "tdp": "125W",
        "socket": "LGA 1200",
        "arq": "Rocket Lake",
        "process": "14nm",
        "l3": "16 MB",
        "year": "2021",
        "igpu": "Intel UHD Graphics 750"
    },
    {
        "name": "Core i5-11600K",
        "cores": "6",
        "threads": "12",
        "maxfrec": "4.9 GHz",
        "tdp": "125W",
        "socket": "LGA 1200",
        "arq": "Rocket Lake",
        "process": "14nm",
        "l3": "12 MB",
        "year": "2021",
        "igpu": "Intel UHD Graphics 750"
    },
    {
        "name": "Core i5-11400",
        "cores": "6",
        "threads": "12",
        "maxfrec": "4.4 GHz",
        "tdp": "65W",
        "socket": "LGA 1200",
        "arq": "Rocket Lake",
        "process": "14nm",
        "l3": "12 MB",
        "year": "2021",
        "igpu": "Intel UHD Graphics 730"
    },
    {
        "name": "Core i3-11100",
        "cores": "4",
        "threads": "8",
        "maxfrec": "4.4 GHz",
        "tdp": "60W",
        "socket": "LGA 1200",
        "arq": "Rocket Lake",
        "process": "14nm",
        "l3": "12 MB",
        "year": "2021",
        "igpu": "Intel UHD Graphics 730"
    }
    ],
    "comet_lake": [
      {
        "name": "Core i9-10900K",
        "cores": "10",
        "threads": "20",
        "maxfrec": "5.3 GHz",
        "tdp": "125W",
        "socket": "LGA 1200",
        "arq": "Comet Lake",
        "process": "14nm",
        "l3": "20 MB",
        "year": "2020",
        "igpu": "Intel UHD Graphics 630"
    },
    {
        "name": "Core i7-10700K",
        "cores": "8",
        "threads": "16",
        "maxfrec": "5.1 GHz",
        "tdp": "125W",
        "socket": "LGA 1200",
        "arq": "Comet Lake",
        "process": "14nm",
        "l3": "16 MB",
        "year": "2020",
        "igpu": "Intel UHD Graphics 630"
    },
    {
        "name": "Core i5-10600K",
        "cores": "6",
        "threads": "12",
        "maxfrec": "4.8 GHz",
        "tdp": "125W",
        "socket": "LGA 1200",
        "arq": "Comet Lake",
        "process": "14nm",
        "l3": "12 MB",
        "year": "2020",
        "igpu": "Intel UHD Graphics 630"
    },
    {
        "name": "Core i5-10400",
        "cores": "6",
        "threads": "12",
        "maxfrec": "4.3 GHz",
        "tdp": "65W",
        "socket": "LGA 1200",
        "arq": "Comet Lake",
        "process": "14nm",
        "l3": "12 MB",
        "year": "2020",
        "igpu": "Intel UHD Graphics 630"
    },
    {
        "name": "Core i3-10100",
        "cores": "4",
        "threads": "8",
        "maxfrec": "4.3 GHz",
        "tdp": "65W",
        "socket": "LGA 1200",
        "arq": "Comet Lake",
        "process": "14nm",
        "l3": "6 MB",
        "year": "2020",
        "igpu": "Intel UHD Graphics 630"
    }
    ],
    "coffee_lake_refresh": [
      {
        "name": "Core i9-9900K",
        "cores": "8",
        "threads": "16",
        "maxfrec": "5.0 GHz",
        "tdp": "95W",
        "socket": "LGA 1151",
        "arq": "Coffee Lake Refresh",
        "process": "14nm",
        "l3": "16 MB",
        "year": "2018",
        "igpu": "Intel UHD Graphics 630"
    },
    {
        "name": "Core i7-9700K",
        "cores": "8",
        "threads": "8",
        "maxfrec": "4.9 GHz",
        "tdp": "95W",
        "socket": "LGA 1151",
        "arq": "Coffee Lake Refresh",
        "process": "14nm",
        "l3": "12 MB",
        "year": "2018",
        "igpu": "Intel UHD Graphics 630"
    },
    {
        "name": "Core i5-9600K",
        "cores": "6",
        "threads": "6",
        "maxfrec": "4.6 GHz",
        "tdp": "95W",
        "socket": "LGA 1151",
        "arq": "Coffee Lake Refresh",
        "process": "14nm",
        "l3": "9 MB",
        "year": "2018",
        "igpu": "Intel UHD Graphics 630"
    },
    {
        "name": "Core i5-9400",
        "cores": "6",
        "threads": "6",
        "maxfrec": "4.1 GHz",
        "tdp": "65W",
        "socket": "LGA 1151",
        "arq": "Coffee Lake Refresh",
        "process": "14nm",
        "l3": "9 MB",
        "year": "2019",
        "igpu": "Intel UHD Graphics 630"
    },
    {
        "name": "Core i3-9100",
        "cores": "4",
        "threads": "4",
        "maxfrec": "4.2 GHz",
        "tdp": "65W",
        "socket": "LGA 1151",
        "arq": "Coffee Lake Refresh",
        "process": "14nm",
        "l3": "6 MB",
        "year": "2019",
        "igpu": "Intel UHD Graphics 630"
    }
    ],
    "coffee_lake": [
      {
        "name": "Core i7-8700K",
        "cores": "6",
        "threads": "12",
        "maxfrec": "4.7 GHz",
        "tdp": "95W",
        "socket": "LGA 1151",
        "arq": "Coffee Lake",
        "process": "14nm",
        "l3": "12 MB",
        "year": "2017",
        "igpu": "Intel UHD Graphics 630"
    },
    {
        "name": "Core i7-8700",
        "cores": "6",
        "threads": "12",
        "maxfrec": "4.6 GHz",
        "tdp": "65W",
        "socket": "LGA 1151",
        "arq": "Coffee Lake",
        "process": "14nm",
        "l3": "12 MB",
        "year": "2017",
        "igpu": "Intel UHD Graphics 630"
    },
    {
        "name": "Core i5-8600K",
        "cores": "6",
        "threads": "6",
        "maxfrec": "4.3 GHz",
        "tdp": "95W",
        "socket": "LGA 1151",
        "arq": "Coffee Lake",
        "process": "14nm",
        "l3": "9 MB",
        "year": "2017",
        "igpu": "Intel UHD Graphics 630"
    },
    {
        "name": "Core i5-8400",
        "cores": "6",
        "threads": "6",
        "maxfrec": "4.0 GHz",
        "tdp": "65W",
        "socket": "LGA 1151",
        "arq": "Coffee Lake",
        "process": "14nm",
        "l3": "9 MB",
        "year": "2017",
        "igpu": "Intel UHD Graphics 630"
    },
    {
        "name": "Core i3-8350K",
        "cores": "4",
        "threads": "4",
        "maxfrec": "4.0 GHz",
        "tdp": "91W",
        "socket": "LGA 1151",
        "arq": "Coffee Lake",
        "process": "14nm",
        "l3": "8 MB",
        "year": "2017",
        "igpu": "Intel UHD Graphics 630"
    },
    {
        "name": "Core i3-8100",
        "cores": "4",
        "threads": "4",
        "maxfrec": "3.6 GHz",
        "tdp": "65W",
        "socket": "LGA 1151",
        "arq": "Coffee Lake",
        "process": "14nm",
        "l3": "6 MB",
        "year": "2017",
        "igpu": "Intel UHD Graphics 630"
    }
    ]
  }

  find(p1:string,p2:string): string{
    return this[p1][p2];
  }

  findByThing(p1:string): string{
    return this[p1];
  }
}
